import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Providers from "@/app/providers";
import Navigation from "@/components/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Infinia Tech Solutions",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="white">
            <body className={`${inter.className} h-full w-full overflow-y-auto overflow-x-hidden antialiased`}>
                <Providers>
                    <Navigation />
                    <main className="relative mx-auto w-full max-w-screen-2xl">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
